### ISSUE TITLE
applyPluginsWaterfall is not a function

### ISSUE THREAD

**Issue by KnisterPeter** [webpack-contrib/html-webpack-plugin#20]
```
TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function
    at /home/marwol/src/ml-webclient-styleguide/node_modules/react-styleguidist/node_modules/html-webpack-plugin/lib/compiler.js:81:51
    at compile (/home/marwol/src/ml-webclient-styleguide/node_modules/webpack/lib/Compiler.js:222:11)
    at hooks.afterCompile.callAsync.err (/home/marwol/src/ml-webclient-styleguide/node_modules/webpack/lib/Compiler.js:470:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/marwol/src/ml-webclient-styleguide/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
...
```

### Config

There is no specific webpack.config.js with the html-webpack-plugin since its a react-styleguidist project which configures this automatically.

**Comment by KnisterPeter** [comment]
Sorry, this was something in my node_modules. After deleting and reinstalling them it works.
